apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: mabdelmeged/myapp:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: myapp-mysql
        - name: DATABASE_USER
          value: myapp
        - name: DATABASE_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: myapp_development