apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-mysql
  template:
    metadata:
      labels:
        app: myapp-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: myapp_development
        - name: MYSQL_USER
          value: myapp
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc