apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-redis
  template:
    metadata:
      labels:
        app: myapp-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
