apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-worker
  template:
    metadata:
      labels:
        app: myapp-worker
    spec:
      volumes:
        - name: script-volume
      containers:
      - name: myapp-worker
        image: mabdelmeged/myapp:latest
        command: ["/bin/bash", "-c"]
        args: ["/myapp/init.sh"]
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: myapp-mysql
        - name: DATABASE_USER
          value: myapp
        - name: DATABASE_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: myapp_development
        - name: RUN_TYPE
          value: worker
        - name: REDIS_HOST
          value: myapp-redis
    